[tool.poetry]
name = "music21-practice"
version = "0.1.0"
description = ""
authors = ["지호 <mmm7407@yonsei.ac.kr>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
music21 = "^9.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
